#!/bin/bash
SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$(cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd)
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR=$(cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd)

function _fn_show_help() {
  echo " (!) This script is deprecated and commands will be removed progressively."
  echo " > 'nuc service' has been moved to 'dctl'"
  echo " > 'nuc create proxy/web' has been moved to 'webctl'"
  echo " > 'nuc backup' has been moved to 'backupctl'"
  echo
  echo "nuc help"
  echo "nuc reboot"
  echo "nuc install <app>"
}

# nuc reboot
function _fn_reboot() {
  apt update
  apt upgrade
  /usr/sbin/reboot
}

# nuc install <app>
function _fn_install_app() {
  echo "Looking for override install script at $DIR/install-scripts/$1..."
  if [ ! -f "$DIR/install-scripts/$1" ]; then
    echo "No install overrides. Trying with apt-get..."
    apt-get install $1
  else
    /bin/bash "$DIR/install-scripts/$1"
  fi
}

case $1 in
reboot)
  _fn_reboot
  ;;
install)
  _fn_install_app $2
  ;;
*)
  _fn_show_help
  ;;
esac
